apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-gitops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/meerolla/k8s-gitops-demo.git
    targetRevision: HEAD
    path: helm/flask-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true